### ISSUE TITLE
FEATURE REQUEST - Add "Cover Only" Theme Variant

### ISSUE THREAD

**Issue by boberr** [anthonycaccese/colorful-simplified-es-de#1]
![Screenshot_20231120_125857](https://github.com/anthonycaccese/colorful-simplified-es-de/assets/46501709/82d6907c-a619-455f-b9db-724bad45a4fb)

Beautiful and very well made theme, but it would be great to have an option to use media from the "covers" folder rather than "miximages" since some games only have a cover. Thank you!

**Comment by anthonycaccese** [comment]
thank you, I will consider it!  Closing this for now but will make sure I add an update to github if I do add it.

**Comment by anthonycaccese** [comment]
that was easy enough to add 😄 

![Screenshot 2023-11-20 at 8 35 21 PM](https://github.com/anthonycaccese/colorful-simplified-es-de/assets/1454947/02f3db77-8312-4af3-afcd-6d2f893546af)

If you get latest from the theme downloader you'll see a new variant for boxart

**Comment by boberr** [comment]
It works great! Jeez that was fast, thanks a bunch for doing it :)

**Comment by anthonycaccese** [comment]
thank you for the suggestion, cheers.
