### ISSUE TITLE
Art work zoomed in and crops miximage marquee / logo out

### ISSUE THREAD

**Issue by dabbler77** [anthonycaccese/colorful-simplified-es-de#5]
Using miximage, it should look like this : https://gitlab.com/es-de/themes/themes-list/-/raw/master/screenshots/colorful-simplified-es-de/colorful-simplified-es-de_02.jpg

However, mine displays with the marquee/logo "cut off" like the image is zoomed in. If I open the "miximage" in a image viewer, the logo is not cut off and is correct.

This is the perfect theme - thanks guys for designing it. Hopefully you have a fix for this issue?

![q4vncfgrnuac1](https://github.com/anthonycaccese/colorful-simplified-es-de/assets/82464780/b164a23d-f93a-4e7b-a3b2-c28fd9c0d60b)

**Comment by anthonycaccese** [comment]
which aspect ratio or screen are you playing on?

**Comment by dabbler77** [comment]
16:10, a steam deck screen

**Comment by anthonycaccese** [comment]
thank you! 16:10 support is in progress (see: https://github.com/anthonycaccese/colorful-simplified-es-de/issues/2).  the above will be addressed as part of that work.  Thank you for the kind words and checking out the theme.

**Comment by dabbler77** [comment]
> thank you! 16:10 support is in progress (see: #2). the above will be addressed as part of that work. Thank you for the kind words and checking out the theme.

Brilliant! Cant wait for the update - thanks for a great design!
